trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: Default
  demands: SpecialSoftware

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: GoTool@0
  inputs:
    version: '1.18.3'


- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/main'
    

